#!/usr/bin/env python3
"""coverage_report.py - UPSCALE coordinate-wrap coverage for Neverhood 4K.

For every module file under engines/neverhood/modules/ counts catalog-matching
coordinate slots (see tools/nhk4k/coordinate_sites.md) that ARE wrapped in
UPSCALE macros vs bare integer literals that are NOT wrapped, and prints a
markdown coverage table. Non-literal expression slots (variables, runtime
values) are reported in their own column; they are excluded from the
percentage because they cannot be judged wrapped/unwrapped mechanically.

Usage: python coverage_report.py [-o output.md]
"""

import argparse
import glob
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from upscale_wrap import (REPO_ROOT, build_ctor_db, analyze_file)  # noqa: E402

MODULES_DIR = os.path.join(REPO_ROOT, "engines", "neverhood", "modules")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", help="write markdown to this file")
    args = ap.parse_args(argv)

    ctor_db = build_ctor_db()
    rows = []
    for path in sorted(glob.glob(os.path.join(MODULES_DIR, "*.cpp"))):
        res, _text = analyze_file(path, ctor_db)
        wrapped = res.wrapped
        unwrapped = len(res.proposals)
        total = wrapped + unwrapped
        pct = (100.0 * wrapped / total) if total else 100.0
        rows.append((os.path.basename(path), total, wrapped, unwrapped,
                     pct, len(res.flags)))

    lines = []
    lines.append("# UPSCALE coordinate coverage (engines/neverhood/modules)")
    lines.append("")
    lines.append("Generated by tools/nhk4k/coverage_report.py. "
                 "`sites total` = wrapped + unwrapped integer-literal "
                 "coordinate slots matched by the catalog "
                 "(tools/nhk4k/coordinate_sites.md). `flagged expr` = "
                 "non-literal coordinate slots needing human review "
                 "(not part of the percentage).")
    lines.append("")
    lines.append("| module | sites total | wrapped | unwrapped | % | flagged expr |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    tt = tw = tu = tf = 0
    for name, total, wrapped, unwrapped, pct, flags in rows:
        lines.append("| %s | %d | %d | %d | %.1f%% | %d |" % (
            name, total, wrapped, unwrapped, pct, flags))
        tt += total
        tw += wrapped
        tu += unwrapped
        tf += flags
    tpct = (100.0 * tw / tt) if tt else 100.0
    lines.append("| **TOTAL** | %d | %d | %d | %.1f%% | %d |" % (
        tt, tw, tu, tpct, tf))
    out = "\n".join(lines) + "\n"
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
        print("wrote %s" % args.output)
    else:
        print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
